#!/usr/bin/env python3
"""Build the compact, v630-compatible modulation-group file.

The source is FlyWire annotations v1.1.0 (July 2023), the release matching
the v630-era materialization used by this project. The selected groups are
neuron identities, not receptor maps or measured chemical concentrations.

Run with a downloaded source table:
  python tools/prepare_modulators.py path/to/Supplemental_file1_annotations.tsv
"""
import csv
import hashlib
import json
import sys
from pathlib import Path

SOURCE = "https://github.com/flyconnectome/flywire_annotations/releases/tag/v1.1.0"


def selected(row):
    if row["hemibrain_type"] == "PAM01" and row["top_nt"] == "dopamine":
        return "daReward"
    if row["hemibrain_type"] == "PPL101" and row["top_nt"] == "dopamine":
        return "daAversive"
    if row["top_nt"] == "octopamine" and (row["cell_type"].startswith("OA-") or row["hemibrain_type"].startswith("OA-")):
        return "octopamine"
    return None


def main():
    source = Path(sys.argv[1]) if len(sys.argv) == 2 else None
    if not source or not source.is_file():
        raise SystemExit("Pass the downloaded v1.1.0 Supplemental_file1_annotations.tsv path.")
    groups = {"daReward": [], "daAversive": [], "octopamine": []}
    with source.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            group = selected(row)
            if group:
                groups[group].append(row["root_id"])
    payload = {
        "format": "flywire-v630-modulation-groups-v1",
        "source": {"repository": "https://github.com/flyconnectome/flywire_annotations", "release": "v1.1.0", "url": SOURCE, "sha256": hashlib.sha256(source.read_bytes()).hexdigest()},
        "selection": {
            "daReward": "hemibrain_type=PAM01 and top_nt=dopamine",
            "daAversive": "hemibrain_type=PPL101 and top_nt=dopamine",
            "octopamine": "top_nt=octopamine and an OA-* cell_type or hemibrain_type",
        },
        "limitations": "These are source neuron identities and transmitter predictions. They are not receptor expression, concentration, or a validated modulation mechanism.",
        "groups": groups,
    }
    output = Path(__file__).resolve().parents[1] / "data" / "modulators.js"
    output.write_text("/* Generated by tools/prepare_modulators.py. */\nglobalThis.ModulationData=" + json.dumps(payload, separators=(",", ":")) + ";\n")
    print(json.dumps({name: len(ids) for name, ids in groups.items()}, indent=2))


if __name__ == "__main__":
    main()
